CHARACTER_REMOVE = {"á": "a",
                    "é": "e",
                    "í": "i",
                    "ó": "o",
                    "ú": "u",
                    "Á": "A",
                    "É": "E",
                    "Í": "I",
                    "Ó": "O",
                    "Ú": "U",
                    "ñ": "n",
                    "Ñ": "N"
                    }

OUT_COLS = ['ID',
            'bathrooms',
            'district',
            'exterior',
            'hasAircon',
            'hasCupboards',
            'hasGarden',
            'hasLift',
            'hasPool',
            'hasStorage',
            'hasTerrace',
            'price',
            'price_per_sm',
            'size',
            'hasFurniture',
            'hasGarage',
            'rooms',
            'north_oriented',
            'east_oriented',
            'west_oriented',
            'south_oriented',
            'hasEquippedKitchen']

IN_COLS = ['ID',
           'bathrooms',
           # 'district',
           'exterior',
           'hasAircon',
           'hasCupboards',
           'hasGarden',
           'hasLift',
           'hasPool',
           'hasStorage',
           'hasTerrace',
           'price',
           'price_per_sm',
           'size',
           'hasFurniture',
           'hasGarage',
           'rooms',
           'north_oriented',
           'east_oriented',
           'west_oriented',
           'south_oriented',
           'hasEquippedKitchen']

OUTLIER_COLS = ["bathrooms", "price", "rooms", "size", "price_per_sm_dev"]

EXCLUDED_COLS = ["ID", "index"]

RANDOM_STATE = 34093458
